import express from "express";
import auth from "../middleware/auth.js";
import authorize from "../middleware/authorize.js";
import { createEvent, deleteEvent, listEvents, updateEvent } from "../controllers/event.controller.js";
const router = express.Router();
router.get("/", auth, listEvents);
router.post("/", auth, authorize("admin", "coach"), createEvent);
router.put("/:id", auth, authorize("admin", "coach"), updateEvent);
router.delete("/:id", auth, authorize("admin", "coach"), deleteEvent);
export default router;
